---
- name: Install vector on RedHat family
  become: true
  ansible.builtin.yum:
    name: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_arch }}.rpm"
    disable_gpg_check: true
  when: ansible_os_family == "RedHat"

- name: Install vector on Debian family
  become: true
  ansible.builtin.apt:
    deb: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
  when: ansible_os_family == "Debian"

- name: Create vector config directory
  become: true
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    mode: "0755"

- name: Deploy vector config
  become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: /etc/vector/vector.yml
    mode: "0644"
  notify: Restart vector service
